services:
  bms-db:
    build:
      context: ./bms-db
    container_name: bms-db
    env_file:
      - .env.db
    volumes:
      - ./bms-db/data:/var/lib/mysql
    networks:
      - bms-network
    ports:
      - "127.0.0.1:3306:3306"
    restart: always

  bms-api:
    build:
      context: ./bms-api
    container_name: bms-api
    env_file:
      - .env
      - .env.api
    environment:
      - DB_HOST=bms-db
      - DB_PORT=3306
      - DATABASE_URL=mysql://bms_user:bms_secure_password@bms-db:3306/bms
    depends_on:
      - bms-db
    networks:
      - bms-network
    restart: always

  bms-proxy:
    build:
      context: ./bms-proxy
    container_name: bms-proxy
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - bms-proxy-certs:/etc/nginx/ssl
      - bms-proxy-acme:/var/www/html
      - bms-proxy-getssl:/root/.getssl
    depends_on:
      - bms-api
    networks:
      - bms-network
    restart: always

volumes:
  bms-proxy-certs:
  bms-proxy-acme:
  bms-proxy-getssl:

networks:
  bms-network:
    driver: bridge
